Add tabBarBadge Carrinho
alexandresjunior/mobile-apps-react-native pull request #1
Opened 2023-02-08 21:28 UTC by DiegoFischerDev

Adiciona o mais um Tab Navigation com contador de itens do carrinho.

2023-02-08 21:29 UTC, DiegoFischerDev commented
Não testei, mas no meu ta mais ou menos assim e funcionou

2023-02-08 21:39 UTC, alexandresjunior commented on ecommerce-app-expo/src/rotas/TabRotas.js
> +    itens.length ? variavel = {tabBarBadge: itens.length} : variavel = {}
podemos resumir tudo isso numa única linha:
`const notificacao = itens.length > 0 ? {tabBarBadge: itens.length} : {}`

troquei o nome de `variavel` para `notificacao` para ficar mais semântico.
podes modificar?

2023-02-08 21:39 UTC, alexandresjunior requested changes
valeu, Diego! adicionei um comentário. podes modificar?

2023-02-08 22:06 UTC, DiegoFischerDev commented on ecommerce-app-expo/src/rotas/TabRotas.js
> +    itens.length ? variavel = {tabBarBadge: itens.length} : variavel = {}
Boa Professor! valeu

2023-02-08 22:19 UTC, DiegoFischerDev commented
Feito!

2023-02-08 22:23 UTC, DiegoFischerDev commented
Agora nesse caso será que da pra notificacao ser um const? a quantidade de itens do carrinho pode variar, vou declarar com let

2023-02-09 11:53 UTC, alexandresjunior approved these changes

2023-02-09 11:54 UTC, alexandresjunior commented
@DiegoFischerDev poderia ser `const` levando em consideração que `itens` é um `state`.

2023-02-09 11:54 UTC, merged